---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kubernetes-external-secrets-alpha-westeu-3
  labels:
    acm-app: kubernetes-external-secrets
spec:
  channel: fusion-operate-ch-helm/channel
  name: kubernetes-external-secrets
  packageFilter:
    version: "0.2.0"
  placement:
    clusterSelector:
      matchLabels:
        zone: alpha-westeu-3
  packageOverrides:
  - packageName: kubernetes-external-secrets
    packageAlias: kubernetes-external-secrets
