---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubernetes-external-secrets
  labels:
    acm-app: kubernetes-external-secrets
spec:
  selector:
    matchLabels:
      acm-app: kubernetes-external-secrets
