---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kubernetes-external-secrets-dev-westeu-1
  labels:
    acm-app: kubernetes-external-secrets
spec:
  channel: fusion-operate-ch-helm/channel
  name: kubernetes-external-secrets
  packageFilter:
    version: "0.2.0"
  placement:
    clusterSelector:
      matchLabels:
        zone: dev-westeu-1
  packageOverrides:
  - packageName: kubernetes-external-secrets
    packageAlias: kubernetes-external-secrets
    packageOverrides:
      - path: spec
        value:
          envVarsFromSecret:
            AZURE_TENANT_ID:
              secretKeyRef: kubernetes-external-test
              key: tenantId
